#!/bin/bash

if [ $(id -u) -ne 0 ]; then
   echo >&2 "Must be run as root"
   exit 1
fi

if [ -z "$START_UDP_STREAM_SCRIPT" ]; then
   echo >&2 "START_UDP_STREAM_SCRIPT must be set"
   exit 1
fi

set -e
set -x

pip install cherrypy==10.2.1 jinja2

sudo -u $NORMAL_USER -H bash <<'EOF'
set -e
set -x

# auto start script
SCRIPT_HOME=~/start_cherrypy
if [ ! -d $SCRIPT_HOME ]; then
    mkdir $SCRIPT_HOME
fi
cp start_cherrypy.sh $SCRIPT_HOME/
cp autostart_cherrypy.sh $SCRIPT_HOME/
cp apsync.py $SCRIPT_HOME/
cp -a html $SCRIPT_HOME/

EOF

sudo -u $NORMAL_USER -H bash <<EOF
set -e
set -x

cp $START_UDP_STREAM_SCRIPT ~/start_cherrypy

EOF


# add line below to bottom of /etc/rc.local to call start script
LINE="sudo -H -u $NORMAL_USER /bin/bash -c '~$NORMAL_USER/start_cherrypy/autostart_cherrypy.sh'"
perl -pe "s%^exit 0%$LINE\\n\\nexit 0%" -i /etc/rc.local
