%YAML:1.0
M1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 554.382712823, 0., 320, 0.,
       415.787034617, 240, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0., 0., 0., 0., 0. ]
M2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 554.382712823, 0., 320, 0.,
       415.787034617, 240, 0., 0., 1. ]
D2: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0., 0., 0., 0., 0. ]

R: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1,0,0,
          0,1,0,
          0,0,1 ]
T: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ -0.2, 0., 0. ]

PreFilterCap: 63
sgbmWinSize: 5
MinDisparity: 0
UniquenessRatio: 80
SpeckleWindowSize: 100
SpeckleRange: 10
Disp12MaxDiff: 1
TextureThreshold: 0
Width: 640
Height: 480
Scale: 1
