#!/bin/bash

if [ $(id -u) -ne 0 ]; then
   echo >&2 "Must be run as root"
   exit 1
fi

set -e
set -x

apt-get install -y \
	strace \
	ltrace \
	tcpdump \
	lsof \
	mlocate \
	v4l-utils \
	usbutils \
	tree \
	wireless-tools \
	can-utils

updatedb
