#!/bin/bash

if [ $(id -u) -ne 0 ]; then
   echo >&2 "Must be run as root"
   exit 1
fi

set -e
set -x

. config.env

pushd ../../Common/Ubuntu/
 ./clean-for-imaging
popd

sudo dd if=/dev/zero of=/zeroes || true
sudo rm -f /zeroes

echo "Success"
